/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as V2SettingsRouteImport } from './routes/v2/settings'
import { Route as V2SessionsRouteImport } from './routes/v2/sessions'
import { Route as V2SearchRouteImport } from './routes/v2/search'
import { Route as V2PricingRouteImport } from './routes/v2/pricing'
import { Route as V2MetricsRouteImport } from './routes/v2/metrics'
import { Route as V2LibraryRouteImport } from './routes/v2/library'
import { Route as V2LedgerRouteImport } from './routes/v2/ledger'
import { Route as V2HomeRouteImport } from './routes/v2/home'
import { Route as V2FleetRouteImport } from './routes/v2/fleet'
import { Route as V2AgentsRouteImport } from './routes/v2/agents'
import { Route as V2AdminRouteImport } from './routes/v2/admin'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as LayoutTopicsRouteImport } from './routes/_layout/topics'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutCasesRouteImport } from './routes/_layout/cases'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as V2SessionsIndexRouteImport } from './routes/v2/sessions.index'
import { Route as V2FleetIndexRouteImport } from './routes/v2/fleet.index'
import { Route as V2SessionsSessionIdRouteImport } from './routes/v2/sessions.$sessionId'
import { Route as V2MetricsMethodologyRouteImport } from './routes/v2/metrics.methodology'
import { Route as V2LibraryDocumentIdRouteImport } from './routes/v2/library.$documentId'
import { Route as V2FleetSessionIdRouteImport } from './routes/v2/fleet.$sessionId'
import { Route as V2AgentsSlugRouteImport } from './routes/v2/agents.$slug'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const V2SettingsRoute = V2SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => V2Route,
} as any)
const V2SessionsRoute = V2SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => V2Route,
} as any)
const V2SearchRoute = V2SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => V2Route,
} as any)
const V2PricingRoute = V2PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => V2Route,
} as any)
const V2MetricsRoute = V2MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => V2Route,
} as any)
const V2LibraryRoute = V2LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => V2Route,
} as any)
const V2LedgerRoute = V2LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => V2Route,
} as any)
const V2HomeRoute = V2HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => V2Route,
} as any)
const V2FleetRoute = V2FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => V2Route,
} as any)
const V2AgentsRoute = V2AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => V2Route,
} as any)
const V2AdminRoute = V2AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => V2Route,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const LayoutTopicsRoute = LayoutTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesRoute = LayoutCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const V2SessionsIndexRoute = V2SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2SessionsRoute,
} as any)
const V2FleetIndexRoute = V2FleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2FleetRoute,
} as any)
const V2SessionsSessionIdRoute = V2SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => V2SessionsRoute,
} as any)
const V2MetricsMethodologyRoute = V2MetricsMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => V2MetricsRoute,
} as any)
const V2LibraryDocumentIdRoute = V2LibraryDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => V2LibraryRoute,
} as any)
const V2FleetSessionIdRoute = V2FleetSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => V2FleetRoute,
} as any)
const V2AgentsSlugRoute = V2AgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => V2AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/v2': typeof V2RouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/cases': typeof LayoutCasesRoute
  '/home': typeof LayoutHomeRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/topics': typeof LayoutTopicsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/v2/admin': typeof V2AdminRoute
  '/v2/agents': typeof V2AgentsRouteWithChildren
  '/v2/fleet': typeof V2FleetRouteWithChildren
  '/v2/home': typeof V2HomeRoute
  '/v2/ledger': typeof V2LedgerRoute
  '/v2/library': typeof V2LibraryRouteWithChildren
  '/v2/metrics': typeof V2MetricsRouteWithChildren
  '/v2/pricing': typeof V2PricingRoute
  '/v2/search': typeof V2SearchRoute
  '/v2/sessions': typeof V2SessionsRouteWithChildren
  '/v2/settings': typeof V2SettingsRoute
  '/docs/': typeof DocsIndexRoute
  '/v2/': typeof V2IndexRoute
  '/v2/agents/$slug': typeof V2AgentsSlugRoute
  '/v2/fleet/$sessionId': typeof V2FleetSessionIdRoute
  '/v2/library/$documentId': typeof V2LibraryDocumentIdRoute
  '/v2/metrics/methodology': typeof V2MetricsMethodologyRoute
  '/v2/sessions/$sessionId': typeof V2SessionsSessionIdRoute
  '/v2/fleet/': typeof V2FleetIndexRoute
  '/v2/sessions/': typeof V2SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/cases': typeof LayoutCasesRoute
  '/home': typeof LayoutHomeRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/topics': typeof LayoutTopicsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/v2/admin': typeof V2AdminRoute
  '/v2/agents': typeof V2AgentsRouteWithChildren
  '/v2/home': typeof V2HomeRoute
  '/v2/ledger': typeof V2LedgerRoute
  '/v2/library': typeof V2LibraryRouteWithChildren
  '/v2/metrics': typeof V2MetricsRouteWithChildren
  '/v2/pricing': typeof V2PricingRoute
  '/v2/search': typeof V2SearchRoute
  '/v2/settings': typeof V2SettingsRoute
  '/docs': typeof DocsIndexRoute
  '/v2': typeof V2IndexRoute
  '/v2/agents/$slug': typeof V2AgentsSlugRoute
  '/v2/fleet/$sessionId': typeof V2FleetSessionIdRoute
  '/v2/library/$documentId': typeof V2LibraryDocumentIdRoute
  '/v2/metrics/methodology': typeof V2MetricsMethodologyRoute
  '/v2/sessions/$sessionId': typeof V2SessionsSessionIdRoute
  '/v2/fleet': typeof V2FleetIndexRoute
  '/v2/sessions': typeof V2SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/v2': typeof V2RouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/cases': typeof LayoutCasesRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/topics': typeof LayoutTopicsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/v2/admin': typeof V2AdminRoute
  '/v2/agents': typeof V2AgentsRouteWithChildren
  '/v2/fleet': typeof V2FleetRouteWithChildren
  '/v2/home': typeof V2HomeRoute
  '/v2/ledger': typeof V2LedgerRoute
  '/v2/library': typeof V2LibraryRouteWithChildren
  '/v2/metrics': typeof V2MetricsRouteWithChildren
  '/v2/pricing': typeof V2PricingRoute
  '/v2/search': typeof V2SearchRoute
  '/v2/sessions': typeof V2SessionsRouteWithChildren
  '/v2/settings': typeof V2SettingsRoute
  '/docs/': typeof DocsIndexRoute
  '/v2/': typeof V2IndexRoute
  '/v2/agents/$slug': typeof V2AgentsSlugRoute
  '/v2/fleet/$sessionId': typeof V2FleetSessionIdRoute
  '/v2/library/$documentId': typeof V2LibraryDocumentIdRoute
  '/v2/metrics/methodology': typeof V2MetricsMethodologyRoute
  '/v2/sessions/$sessionId': typeof V2SessionsSessionIdRoute
  '/v2/fleet/': typeof V2FleetIndexRoute
  '/v2/sessions/': typeof V2SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/landing'
    | '/login'
    | '/pricing'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/v2'
    | '/admin'
    | '/cases'
    | '/home'
    | '/settings'
    | '/skills'
    | '/topics'
    | '/docs/$slug'
    | '/v2/admin'
    | '/v2/agents'
    | '/v2/fleet'
    | '/v2/home'
    | '/v2/ledger'
    | '/v2/library'
    | '/v2/metrics'
    | '/v2/pricing'
    | '/v2/search'
    | '/v2/sessions'
    | '/v2/settings'
    | '/docs/'
    | '/v2/'
    | '/v2/agents/$slug'
    | '/v2/fleet/$sessionId'
    | '/v2/library/$documentId'
    | '/v2/metrics/methodology'
    | '/v2/sessions/$sessionId'
    | '/v2/fleet/'
    | '/v2/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/pricing'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/cases'
    | '/home'
    | '/settings'
    | '/skills'
    | '/topics'
    | '/docs/$slug'
    | '/v2/admin'
    | '/v2/agents'
    | '/v2/home'
    | '/v2/ledger'
    | '/v2/library'
    | '/v2/metrics'
    | '/v2/pricing'
    | '/v2/search'
    | '/v2/settings'
    | '/docs'
    | '/v2'
    | '/v2/agents/$slug'
    | '/v2/fleet/$sessionId'
    | '/v2/library/$documentId'
    | '/v2/metrics/methodology'
    | '/v2/sessions/$sessionId'
    | '/v2/fleet'
    | '/v2/sessions'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/docs'
    | '/landing'
    | '/login'
    | '/pricing'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/v2'
    | '/_layout/admin'
    | '/_layout/cases'
    | '/_layout/home'
    | '/_layout/settings'
    | '/_layout/skills'
    | '/_layout/topics'
    | '/docs/$slug'
    | '/v2/admin'
    | '/v2/agents'
    | '/v2/fleet'
    | '/v2/home'
    | '/v2/ledger'
    | '/v2/library'
    | '/v2/metrics'
    | '/v2/pricing'
    | '/v2/search'
    | '/v2/sessions'
    | '/v2/settings'
    | '/docs/'
    | '/v2/'
    | '/v2/agents/$slug'
    | '/v2/fleet/$sessionId'
    | '/v2/library/$documentId'
    | '/v2/metrics/methodology'
    | '/v2/sessions/$sessionId'
    | '/v2/fleet/'
    | '/v2/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  V2Route: typeof V2RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof V2Route
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/v2/settings': {
      id: '/v2/settings'
      path: '/settings'
      fullPath: '/v2/settings'
      preLoaderRoute: typeof V2SettingsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/sessions': {
      id: '/v2/sessions'
      path: '/sessions'
      fullPath: '/v2/sessions'
      preLoaderRoute: typeof V2SessionsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/search': {
      id: '/v2/search'
      path: '/search'
      fullPath: '/v2/search'
      preLoaderRoute: typeof V2SearchRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/pricing': {
      id: '/v2/pricing'
      path: '/pricing'
      fullPath: '/v2/pricing'
      preLoaderRoute: typeof V2PricingRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/metrics': {
      id: '/v2/metrics'
      path: '/metrics'
      fullPath: '/v2/metrics'
      preLoaderRoute: typeof V2MetricsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/library': {
      id: '/v2/library'
      path: '/library'
      fullPath: '/v2/library'
      preLoaderRoute: typeof V2LibraryRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/ledger': {
      id: '/v2/ledger'
      path: '/ledger'
      fullPath: '/v2/ledger'
      preLoaderRoute: typeof V2LedgerRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/home': {
      id: '/v2/home'
      path: '/home'
      fullPath: '/v2/home'
      preLoaderRoute: typeof V2HomeRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/fleet': {
      id: '/v2/fleet'
      path: '/fleet'
      fullPath: '/v2/fleet'
      preLoaderRoute: typeof V2FleetRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/agents': {
      id: '/v2/agents'
      path: '/agents'
      fullPath: '/v2/agents'
      preLoaderRoute: typeof V2AgentsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/admin': {
      id: '/v2/admin'
      path: '/admin'
      fullPath: '/v2/admin'
      preLoaderRoute: typeof V2AdminRouteImport
      parentRoute: typeof V2Route
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_layout/topics': {
      id: '/_layout/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof LayoutTopicsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases': {
      id: '/_layout/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof LayoutCasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/v2/sessions/': {
      id: '/v2/sessions/'
      path: '/'
      fullPath: '/v2/sessions/'
      preLoaderRoute: typeof V2SessionsIndexRouteImport
      parentRoute: typeof V2SessionsRoute
    }
    '/v2/fleet/': {
      id: '/v2/fleet/'
      path: '/'
      fullPath: '/v2/fleet/'
      preLoaderRoute: typeof V2FleetIndexRouteImport
      parentRoute: typeof V2FleetRoute
    }
    '/v2/sessions/$sessionId': {
      id: '/v2/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/v2/sessions/$sessionId'
      preLoaderRoute: typeof V2SessionsSessionIdRouteImport
      parentRoute: typeof V2SessionsRoute
    }
    '/v2/metrics/methodology': {
      id: '/v2/metrics/methodology'
      path: '/methodology'
      fullPath: '/v2/metrics/methodology'
      preLoaderRoute: typeof V2MetricsMethodologyRouteImport
      parentRoute: typeof V2MetricsRoute
    }
    '/v2/library/$documentId': {
      id: '/v2/library/$documentId'
      path: '/$documentId'
      fullPath: '/v2/library/$documentId'
      preLoaderRoute: typeof V2LibraryDocumentIdRouteImport
      parentRoute: typeof V2LibraryRoute
    }
    '/v2/fleet/$sessionId': {
      id: '/v2/fleet/$sessionId'
      path: '/$sessionId'
      fullPath: '/v2/fleet/$sessionId'
      preLoaderRoute: typeof V2FleetSessionIdRouteImport
      parentRoute: typeof V2FleetRoute
    }
    '/v2/agents/$slug': {
      id: '/v2/agents/$slug'
      path: '/$slug'
      fullPath: '/v2/agents/$slug'
      preLoaderRoute: typeof V2AgentsSlugRouteImport
      parentRoute: typeof V2AgentsRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCasesRoute: typeof LayoutCasesRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutTopicsRoute: typeof LayoutTopicsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCasesRoute: LayoutCasesRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutTopicsRoute: LayoutTopicsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface V2AgentsRouteChildren {
  V2AgentsSlugRoute: typeof V2AgentsSlugRoute
}

const V2AgentsRouteChildren: V2AgentsRouteChildren = {
  V2AgentsSlugRoute: V2AgentsSlugRoute,
}

const V2AgentsRouteWithChildren = V2AgentsRoute._addFileChildren(
  V2AgentsRouteChildren,
)

interface V2FleetRouteChildren {
  V2FleetSessionIdRoute: typeof V2FleetSessionIdRoute
  V2FleetIndexRoute: typeof V2FleetIndexRoute
}

const V2FleetRouteChildren: V2FleetRouteChildren = {
  V2FleetSessionIdRoute: V2FleetSessionIdRoute,
  V2FleetIndexRoute: V2FleetIndexRoute,
}

const V2FleetRouteWithChildren =
  V2FleetRoute._addFileChildren(V2FleetRouteChildren)

interface V2LibraryRouteChildren {
  V2LibraryDocumentIdRoute: typeof V2LibraryDocumentIdRoute
}

const V2LibraryRouteChildren: V2LibraryRouteChildren = {
  V2LibraryDocumentIdRoute: V2LibraryDocumentIdRoute,
}

const V2LibraryRouteWithChildren = V2LibraryRoute._addFileChildren(
  V2LibraryRouteChildren,
)

interface V2MetricsRouteChildren {
  V2MetricsMethodologyRoute: typeof V2MetricsMethodologyRoute
}

const V2MetricsRouteChildren: V2MetricsRouteChildren = {
  V2MetricsMethodologyRoute: V2MetricsMethodologyRoute,
}

const V2MetricsRouteWithChildren = V2MetricsRoute._addFileChildren(
  V2MetricsRouteChildren,
)

interface V2SessionsRouteChildren {
  V2SessionsSessionIdRoute: typeof V2SessionsSessionIdRoute
  V2SessionsIndexRoute: typeof V2SessionsIndexRoute
}

const V2SessionsRouteChildren: V2SessionsRouteChildren = {
  V2SessionsSessionIdRoute: V2SessionsSessionIdRoute,
  V2SessionsIndexRoute: V2SessionsIndexRoute,
}

const V2SessionsRouteWithChildren = V2SessionsRoute._addFileChildren(
  V2SessionsRouteChildren,
)

interface V2RouteChildren {
  V2AdminRoute: typeof V2AdminRoute
  V2AgentsRoute: typeof V2AgentsRouteWithChildren
  V2FleetRoute: typeof V2FleetRouteWithChildren
  V2HomeRoute: typeof V2HomeRoute
  V2LedgerRoute: typeof V2LedgerRoute
  V2LibraryRoute: typeof V2LibraryRouteWithChildren
  V2MetricsRoute: typeof V2MetricsRouteWithChildren
  V2PricingRoute: typeof V2PricingRoute
  V2SearchRoute: typeof V2SearchRoute
  V2SessionsRoute: typeof V2SessionsRouteWithChildren
  V2SettingsRoute: typeof V2SettingsRoute
  V2IndexRoute: typeof V2IndexRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2AdminRoute: V2AdminRoute,
  V2AgentsRoute: V2AgentsRouteWithChildren,
  V2FleetRoute: V2FleetRouteWithChildren,
  V2HomeRoute: V2HomeRoute,
  V2LedgerRoute: V2LedgerRoute,
  V2LibraryRoute: V2LibraryRouteWithChildren,
  V2MetricsRoute: V2MetricsRouteWithChildren,
  V2PricingRoute: V2PricingRoute,
  V2SearchRoute: V2SearchRoute,
  V2SessionsRoute: V2SessionsRouteWithChildren,
  V2SettingsRoute: V2SettingsRoute,
  V2IndexRoute: V2IndexRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  V2Route: V2RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
