/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as V2SearchRouteImport } from './routes/v2/search'
import { Route as V2PricingRouteImport } from './routes/v2/pricing'
import { Route as V2MetricsRouteImport } from './routes/v2/metrics'
import { Route as V2LibraryRouteImport } from './routes/v2/library'
import { Route as V2HomeRouteImport } from './routes/v2/home'
import { Route as V2AgentsRouteImport } from './routes/v2/agents'
import { Route as V2AdminRouteImport } from './routes/v2/admin'
import { Route as LayoutTopicsRouteImport } from './routes/_layout/topics'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutCasesRouteImport } from './routes/_layout/cases'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as V2MetricsMethodologyRouteImport } from './routes/v2/metrics.methodology'
import { Route as V2LibraryDocumentIdRouteImport } from './routes/v2/library.$documentId'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any)
const V2SearchRoute = V2SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => V2Route,
} as any)
const V2PricingRoute = V2PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => V2Route,
} as any)
const V2MetricsRoute = V2MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => V2Route,
} as any)
const V2LibraryRoute = V2LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => V2Route,
} as any)
const V2HomeRoute = V2HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => V2Route,
} as any)
const V2AgentsRoute = V2AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => V2Route,
} as any)
const V2AdminRoute = V2AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => V2Route,
} as any)
const LayoutTopicsRoute = LayoutTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesRoute = LayoutCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const V2MetricsMethodologyRoute = V2MetricsMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => V2MetricsRoute,
} as any)
const V2LibraryDocumentIdRoute = V2LibraryDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => V2LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/v2': typeof V2RouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/cases': typeof LayoutCasesRoute
  '/home': typeof LayoutHomeRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/topics': typeof LayoutTopicsRoute
  '/v2/admin': typeof V2AdminRoute
  '/v2/agents': typeof V2AgentsRoute
  '/v2/home': typeof V2HomeRoute
  '/v2/library': typeof V2LibraryRouteWithChildren
  '/v2/metrics': typeof V2MetricsRouteWithChildren
  '/v2/pricing': typeof V2PricingRoute
  '/v2/search': typeof V2SearchRoute
  '/v2/': typeof V2IndexRoute
  '/v2/library/$documentId': typeof V2LibraryDocumentIdRoute
  '/v2/metrics/methodology': typeof V2MetricsMethodologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/cases': typeof LayoutCasesRoute
  '/home': typeof LayoutHomeRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/topics': typeof LayoutTopicsRoute
  '/v2/admin': typeof V2AdminRoute
  '/v2/agents': typeof V2AgentsRoute
  '/v2/home': typeof V2HomeRoute
  '/v2/library': typeof V2LibraryRouteWithChildren
  '/v2/metrics': typeof V2MetricsRouteWithChildren
  '/v2/pricing': typeof V2PricingRoute
  '/v2/search': typeof V2SearchRoute
  '/v2': typeof V2IndexRoute
  '/v2/library/$documentId': typeof V2LibraryDocumentIdRoute
  '/v2/metrics/methodology': typeof V2MetricsMethodologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/v2': typeof V2RouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/cases': typeof LayoutCasesRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/topics': typeof LayoutTopicsRoute
  '/v2/admin': typeof V2AdminRoute
  '/v2/agents': typeof V2AgentsRoute
  '/v2/home': typeof V2HomeRoute
  '/v2/library': typeof V2LibraryRouteWithChildren
  '/v2/metrics': typeof V2MetricsRouteWithChildren
  '/v2/pricing': typeof V2PricingRoute
  '/v2/search': typeof V2SearchRoute
  '/v2/': typeof V2IndexRoute
  '/v2/library/$documentId': typeof V2LibraryDocumentIdRoute
  '/v2/metrics/methodology': typeof V2MetricsMethodologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/v2'
    | '/admin'
    | '/cases'
    | '/home'
    | '/settings'
    | '/skills'
    | '/topics'
    | '/v2/admin'
    | '/v2/agents'
    | '/v2/home'
    | '/v2/library'
    | '/v2/metrics'
    | '/v2/pricing'
    | '/v2/search'
    | '/v2/'
    | '/v2/library/$documentId'
    | '/v2/metrics/methodology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/cases'
    | '/home'
    | '/settings'
    | '/skills'
    | '/topics'
    | '/v2/admin'
    | '/v2/agents'
    | '/v2/home'
    | '/v2/library'
    | '/v2/metrics'
    | '/v2/pricing'
    | '/v2/search'
    | '/v2'
    | '/v2/library/$documentId'
    | '/v2/metrics/methodology'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/v2'
    | '/_layout/admin'
    | '/_layout/cases'
    | '/_layout/home'
    | '/_layout/settings'
    | '/_layout/skills'
    | '/_layout/topics'
    | '/v2/admin'
    | '/v2/agents'
    | '/v2/home'
    | '/v2/library'
    | '/v2/metrics'
    | '/v2/pricing'
    | '/v2/search'
    | '/v2/'
    | '/v2/library/$documentId'
    | '/v2/metrics/methodology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  V2Route: typeof V2RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/search': {
      id: '/v2/search'
      path: '/search'
      fullPath: '/v2/search'
      preLoaderRoute: typeof V2SearchRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/pricing': {
      id: '/v2/pricing'
      path: '/pricing'
      fullPath: '/v2/pricing'
      preLoaderRoute: typeof V2PricingRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/metrics': {
      id: '/v2/metrics'
      path: '/metrics'
      fullPath: '/v2/metrics'
      preLoaderRoute: typeof V2MetricsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/library': {
      id: '/v2/library'
      path: '/library'
      fullPath: '/v2/library'
      preLoaderRoute: typeof V2LibraryRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/home': {
      id: '/v2/home'
      path: '/home'
      fullPath: '/v2/home'
      preLoaderRoute: typeof V2HomeRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/agents': {
      id: '/v2/agents'
      path: '/agents'
      fullPath: '/v2/agents'
      preLoaderRoute: typeof V2AgentsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/admin': {
      id: '/v2/admin'
      path: '/admin'
      fullPath: '/v2/admin'
      preLoaderRoute: typeof V2AdminRouteImport
      parentRoute: typeof V2Route
    }
    '/_layout/topics': {
      id: '/_layout/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof LayoutTopicsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases': {
      id: '/_layout/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof LayoutCasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/v2/metrics/methodology': {
      id: '/v2/metrics/methodology'
      path: '/methodology'
      fullPath: '/v2/metrics/methodology'
      preLoaderRoute: typeof V2MetricsMethodologyRouteImport
      parentRoute: typeof V2MetricsRoute
    }
    '/v2/library/$documentId': {
      id: '/v2/library/$documentId'
      path: '/$documentId'
      fullPath: '/v2/library/$documentId'
      preLoaderRoute: typeof V2LibraryDocumentIdRouteImport
      parentRoute: typeof V2LibraryRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCasesRoute: typeof LayoutCasesRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutTopicsRoute: typeof LayoutTopicsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCasesRoute: LayoutCasesRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutTopicsRoute: LayoutTopicsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface V2LibraryRouteChildren {
  V2LibraryDocumentIdRoute: typeof V2LibraryDocumentIdRoute
}

const V2LibraryRouteChildren: V2LibraryRouteChildren = {
  V2LibraryDocumentIdRoute: V2LibraryDocumentIdRoute,
}

const V2LibraryRouteWithChildren = V2LibraryRoute._addFileChildren(
  V2LibraryRouteChildren,
)

interface V2MetricsRouteChildren {
  V2MetricsMethodologyRoute: typeof V2MetricsMethodologyRoute
}

const V2MetricsRouteChildren: V2MetricsRouteChildren = {
  V2MetricsMethodologyRoute: V2MetricsMethodologyRoute,
}

const V2MetricsRouteWithChildren = V2MetricsRoute._addFileChildren(
  V2MetricsRouteChildren,
)

interface V2RouteChildren {
  V2AdminRoute: typeof V2AdminRoute
  V2AgentsRoute: typeof V2AgentsRoute
  V2HomeRoute: typeof V2HomeRoute
  V2LibraryRoute: typeof V2LibraryRouteWithChildren
  V2MetricsRoute: typeof V2MetricsRouteWithChildren
  V2PricingRoute: typeof V2PricingRoute
  V2SearchRoute: typeof V2SearchRoute
  V2IndexRoute: typeof V2IndexRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2AdminRoute: V2AdminRoute,
  V2AgentsRoute: V2AgentsRoute,
  V2HomeRoute: V2HomeRoute,
  V2LibraryRoute: V2LibraryRouteWithChildren,
  V2MetricsRoute: V2MetricsRouteWithChildren,
  V2PricingRoute: V2PricingRoute,
  V2SearchRoute: V2SearchRoute,
  V2IndexRoute: V2IndexRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  V2Route: V2RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
